### ISSUE TITLE
You are so great！！

### ISSUE THREAD

**Issue by z234009184** [jonataslaw/get_server#14]
Thanks for your Get_server, It's useful to me!!

**Comment by idootop** [comment]
> 
> 
> Thanks for your Get_server, It's useful to me!!

你的蛋播星球也很great！
PS: 你主页上的resume或许可以设置成私有仓库，
不然从你的commit历史记录里也可以看到你的所有个人信息，当心哟~
Good luck :)

**Comment by z234009184** [comment]
好的，谢谢提醒😄




------------------ Original ------------------
