### ISSUE TITLE
Does this package work on Flutter Web?

### ISSUE THREAD

**Issue by AliaksandrBadretdzinau** [jonataslaw/get_server#23]
Hey. I am developing a Flutter web application and am trying to implement an HTTP server.
The _dart:io_ library not working on Web
Is this library an exception?

**Comment by joe-getcouragenow** [comment]
https://github.com/gskinnerTeam/flutter-universal-platform

**Comment by AliaksandrBadretdzinau** [comment]
> 
> 
> https://github.com/gskinnerTeam/flutter-universal-platform

Hey, can you describe your answer?

**Comment by jonataslaw** [comment]
This is a package that builds a server application. HttpServer is a dependency on dart:io, so what you want is not possible with dart, so I am closing this.
