### ISSUE TITLE
How to start get_server?

### ISSUE THREAD

**Issue by Hopheylalal** [jonataslaw/get_server#25]
I do not understand how to start get_server  and then go to localhost

**Comment by CpdnCristiano** [comment]
Run
`dart  lib/main.dart`

**Comment by Bes79** [comment]
this is not work for me (

dart lib/main.dart                                                                                        
lib/main.dart: Warning: Interpreting this as package URI, 'package:crmdb_server/main.dart'.                                                                 Unhandled exception:                                                                                                                                        
SignalException: Failed to listen for SIGTERM, osError: OS Error: Такой запрос не поддерживается.                                                           , errno = 50

**Comment by prakash-indorkar** [comment]
Not working for me either... :(

lib/main.dart: Warning: Interpreting this as package URI, 'package:scServer/main.dart'.
Unhandled exception:

SocketException: Failed to create server socket (OS Error: An attempt was made to access a socket in a way forbidden by its access permissions.
, errno = 10013), address = 0.0.0.0, port = 8080

**Comment by mjablecnik** [comment]
Can you write here what is your operating system and environment where are you trying start the get_server example?
I have Linux Mint 19.3
and after run commands in terminal shell:
```
git clone git@github.com:jonataslaw/get_server.git
cd get_server/example
flutter packages pub get
dart lib/main.dart
```
and `curl localhost:8080` in other terminal tab it works..

**Comment by easazade** [comment]
try  using `dart run lib/main.dart`

**Comment by jonataslaw** [comment]
In the example case, the error occurred because the default port was busy. Just set another port (and open it on the firewall if you have one) and everything will work
If you're using windows, try starting dart, or the package compiled as administrator, if you run into problems, and that's all.

**Comment by ec2-learn-instant** [comment]
Can you please explain the procedure to start the app on different port? @jonataslaw

**Comment by jonataslaw** [comment]
Yeah, for sure:

```dart
GetServer(
    port: 80, // or 8080, or 3000, or whatever you want
```
