### ISSUE TITLE
Sometimes work, sometimes not.

### ISSUE THREAD

**Issue by atfa** [jonataslaw/get_server#26]
The Get Server sometimes work , sometimes not.

# 1. main.dart
void main() {
  runApp(GetServer(
    getPages: [
      GetPage(name: '/', page: () => Home()),
    ],
  ));
}

class Home extends GetView {
  @override
  Widget build(BuildContext context) {
    return Text("Welcome to GetX");
  }
}

# 2. Run it.
Connecting to VM Service at ws://127.0.0.1:35359/VG1o4-TiZtg=/ws
lib/main.dart: Warning: Interpreting this as package URI, 'package:cool_server/main.dart'.
[GETX] Starting server on 127.0.0.1:8080 using 4 threads

# 3. Try it.
$ curl 127.0.0.1:8080        
Welcome to GetX
$ curl 127.0.0.1:8080
$ curl 127.0.0.1:8080
$ curl 127.0.0.1:8080
$ curl 127.0.0.1:8080
$ curl 127.0.0.1:8080
$ curl 127.0.0.1:8080
Welcome to GetX
$ curl 127.0.0.1:8080

# 4. Look at the server.
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /
[GETX] Method GET on /

**Comment by jonataslaw** [comment]
I try it:

```
[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ curl 127.0.0.1:8080
Hello world[jonny@jonny ~]$ 
```

Please update the package to last version, all bugs are fixed
