### ISSUE TITLE
How can i see logcat

### ISSUE THREAD

**Issue by huutho-dev** [jonataslaw/get_server#28]
I cannot found any log from terminal? How can i see the log print from GetServer

**Comment by jonataslaw** [comment]
Start on debug mode, in release all log are suppress for security reasons

**Comment by huutho-dev** [comment]
Oh thanks. It works fine on VsCode, but it doesn't work on AndroidStudio

**Comment by huutho-dev** [comment]
Maybe bug from IDE
https://github.com/flutter/flutter/issues/47913
