### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by huutho-dev** [jonataslaw/get_server#29]
![image](https://user-images.githubusercontent.com/14016488/103328449-8bb90480-4a8b-11eb-88f0-1018be3857b1.png)

Server crashed when running pageable

**Comment by huutho-dev** [comment]
![image](https://user-images.githubusercontent.com/14016488/103328563-ed796e80-4a8b-11eb-86ad-8b60af72d3c7.png)
Comments like above image will work

(Sr my bad English)

**Comment by Katekko** [comment]
Can you pass the full example so I can reproduce my self here.

**Comment by huutho-dev** [comment]
> Can you pass the full example so I can reproduce my self here.

I run the code at the branch master
https://github.com/jonataslaw/get_server
http://localhost:8080/pageable

**Comment by jonataslaw** [comment]
I can't reproduce this in the latest version, so closing this
