### ISSUE TITLE
How to get params from @Body 

### ISSUE THREAD

**Issue by huutho-dev** [jonataslaw/get_server#33]
![image](https://user-images.githubusercontent.com/14016488/104095879-d4629000-52cb-11eb-9445-f52f46692253.png)
![image](https://user-images.githubusercontent.com/14016488/104095893-e5130600-52cb-11eb-9b06-276840181b80.png)
I'm test from Postman, method @POST, and pass param as Body key-value (I don't want put param as segments in uri)
But server alway print null or empty like image. :( 
Thanks

**Comment by huutho-dev** [comment]
I got it from the payload, I love this package

**Comment by rambozzang** [comment]
> I got it from the payload, I love this package

hey guy , How to use the payload?

**Comment by lnmproj** [comment]
@huutho-dev Can you please give an example

**Comment by lnmproj** [comment]
@rambozzang  Can you please give an example
