### ISSUE TITLE
useLog not working

### ISSUE THREAD

**Issue by julianoventola** [jonataslaw/get_server#34]
GREAT work with get_server, it's an amazing package! ❤️ 
I know the flag for useLog is true by default, but it is no logging (tested in GET, POST - Multicores handler)
i am using:  get_server: ^0.91.0
![image](https://user-images.githubusercontent.com/28475558/104114336-2e6e5000-52e2-11eb-9368-8e95401ebf5e.png)

**Comment by jonataslaw** [comment]
Does this problem still exist?
dart:developer couldn't show logs in production, only when the app was debugging. Is that your case?

**Comment by julianoventola** [comment]
I guess i was not running in debug mode, but thank you for the attention.
Maybe you would like to see "alfred" package, it's very interesting for backend too
