### ISSUE TITLE
Flutter web not Rendering

### ISSUE THREAD

**Issue by kingrupam** [jonataslaw/get_server#41]
import 'dart:io';
import 'package:get_server/get_server.dart';

void main() {
  runApp(
    GetServer(
      port: 21023,
      // host: '127.0.0.1',
      home: Home(),
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Html(path: '${Directory.current.path}/web/index.html');
  }
}

<img width="650" alt="Screenshot_1" src="https://user-images.githubusercontent.com/69413695/110355456-41419e80-805f-11eb-9e9d-ee6742da94fb.png">

**Comment by jonataslaw** [comment]
Please, read the readme. You need to use public folder to Flutter web, because it is not a single html file
