### ISSUE TITLE
cannot return a json page as per example

### ISSUE THREAD

**Issue by Shreemanarjun** [jonataslaw/get_server#45]
**Error**

Unhandled exception:
NoSuchMethodError: Class '_InternalLinkedHashMap<String, String>' has no instance method 'toJson'.
Receiver: _LinkedHashMap len:1
Tried calling: toJson()

**Comment by rambozzang** [comment]
hey~.  Modify it like this 

socket_notifier.dart line 51,

  //  final data = msg['data'];
      final data = jsonEncode(msg['data']);

**Comment by makao007** [comment]
Hi, This is Demo that I run OK in Android Simulator.
`
class Json1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(jsonEncode({
      "fruits": "xxx"
    }));
  }
}`

**Comment by jonataslaw** [comment]
I can't reproduce this in the latest version, so closing this
