### ISSUE TITLE
page not found in Android Simulator Fluttter APP with static folder

### ISSUE THREAD

**Issue by makao007** [jonataslaw/get_server#46]
Hi, I try to run the get_server in a flutter app on Android Simulator, 
I can return a Text('Hello') , but when I set a static folder, the page not found.
home: FolderWidget('web') // not found the folder

>   runApp(GetServer(
    host: '0.0.0.0',
    port: 8088,
    home: FolderWidget('web', allowDirectoryListing:true),
    getPages: [
      GetPage(name: '/hello',  page:()=>Text('Hello')),
    ],
  ));

**Comment by makao007** [comment]
I know the reason now.
That is because the flutter code can not find the folder, You can create a folder in getApplicationDocumentsDirectory and copy files into the above folder and then FolderWidget(the full folder above)

**Comment by jonataslaw** [comment]
Glad you found the solution. Based on your comment, I'm closing this
