### ISSUE TITLE
jwt problem

### ISSUE THREAD

**Issue by yakupbaser** [jonataslaw/get_server#55]
hi,
thanks for your wonderfull package. I opened example, main page works well. But fruits page doesnt, because of needs auth. So i tryed to open 'localhost:8080/auth' page with post method for take a jwt. But it gives an error like this:

`Unhandled exception:
"String" not found. You need to call "Get.put(String())" or "Get.lazyPut(()=>String())"
#0      GetInstance.find (package:get_server/src/framework/get_instance/src/get_instance.dart:332:7)
#1      Inst.find (package:get_server/src/framework/get_instance/src/extension_instance.dart:70:45)
#2      TokenUtil.getJwtKey (package:get_server/src/core/src/utils/token_util.dart:24:19)
#3      TokenUtil.generateToken (package:get_server/src/core/src/utils/token_util.dart:6:17)
#4      AuthController.getToken (package:buyboxserver/pages/auth/controller/view_controller.dart:13:22)
#5      AuthPage.build (package:buyboxserver/pages/auth/view/auth.dart:8:28)
#6      StatelessElement.build (package:get_server/src/core/src/widgets/widget.dart:165:28)
#7      StatelessElement.performRebuild (package:get_server/src/core/src/widgets/widget.dart:158:5)
#8      new StatelessElement (package:get_server/src/core/src/widgets/widget.dart:153:5)
#9      StatelessWidget.createElement (package:get_server/src/core/src/widgets/widget.dart:139:12)
#10     Route._sendResponse (package:get_server/src/routes/route.dart:99:15)
#11     Route.handle.<anonymous closure> (package:get_server/src/routes/route.dart:86:11)
#12     Route._verifyAuth (package:get_server/src/routes/route.dart:150:22)
#13     Route.handle (package:get_server/src/routes/route.dart:77:5)
#14     GetServerController.startServer.<anonymous closure> (package:get_server/src/core/src/server_main_controller.dart:95:17)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#19     _StreamController._add (dart:async/stream_controller.dart:607:7)
#20     _StreamController.add (dart:async/stream_controller.dart:554:5)
#21     _HttpServer._handleRequest (dart:_http/http_impl.dart:3209:19)
#22     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2964:19)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#27     _StreamController._add (dart:async/stream_controller.dart:607:7)
#28     _StreamController.add (dart:async/stream_controller.dart:554:5)
#29     _HttpParser._headersEnd (dart:_http/http_parser.dart:394:19)
#30     _HttpParser._doParse (dart:_http/http_parser.dart:750:15)
#31     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#32     _HttpParser._onData (dart:_http/http_parser.dart:878:5)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#37     _StreamController._add (dart:async/stream_controller.dart:607:7)
#38     _StreamController.add (dart:async/stream_controller.dart:554:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#40     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#44     _StreamController._add (dart:async/stream_controller.dart:607:7)
#45     _StreamController.add (dart:async/stream_controller.dart:554:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
Macs-MacBook-Pro:buyboxserver macpro$ dart run lib/main.dart`

So how can i use auth, i guess the 'localhost:8080/auth' page should give a jwt to me or im wrong. Please tell me more about how to use jwt on get_server package. Your document doesnt look enough for it.

**Comment by odunboye** [comment]
I remember fixing this on my branch, will send a PR

**Comment by odunboye** [comment]
@jonataslaw, I have sent a PR for this, #58 kindly review.

**Comment by jonataslaw** [comment]
closed by https://github.com/jonataslaw/get_server/pull/58
