### ISSUE TITLE
How to run the server app in the background of a flutter app?

### ISSUE THREAD

**Issue by blueeyestw** [jonataslaw/get_server#78]
I want to create a Flutter video player app that concurrently hosts a file server in the background. Is it possible with this package?
Will both apps (UI app and backend app) be able to communicate with each other during runtime?

**Comment by hoo0** [comment]
1. make "server.dart" (sample file)
2. in main.dart
...
import './server.dart' as server;

void main() {
  runApp(const MyApp());
  server.main();
}
