### ISSUE TITLE
Custom Response - Empty list as json

### ISSUE THREAD

**Issue by julianoventola** [jonataslaw/get_server#82]
Please, how can i send a custom response? 

I want to send a empty list (because i will add items later) but as a content type as json

**Comment by jonataslaw** [comment]
try the version 1.2.1, I think It was fixed

**Comment by julianoventola** [comment]
It's working! Thank you! @jonataslaw 

The way i was trying 😂
![image](https://user-images.githubusercontent.com/28475558/174806185-9cba58e8-88b2-4f92-94f0-46d216b46a04.png)
