### ISSUE TITLE
``` Apache License Copyright Request ``` Wish to modify some of source code for my own project 

### ISSUE THREAD

**Issue by Manishmg3994** [jonataslaw/get_server#90]
I wish to modify some of core concepts used in your this package but as you have issued a Apache License for copyright holders , I wish you will provide me all those Request permissions, so that I can modify code and make it suitable for my projects 
## * Thanks in advance *

**Comment by jonataslaw** [comment]
Go ahead, I will change the licence to MIT because there is no reason for apache.
You can use it, and modify as you need.

**Comment by Manishmg3994** [comment]
Thanks man, Your package is super duper awesome
